### ISSUE TITLE
Remove the first occurrence of a specified element from an array

### ISSUE THREAD

**Issue by kekslv** [NazikCompany/PythonLearning#3]
Write a Python program to remove the first occurrence of a specified element from an array. 
Sample Output:
Original array:  [1, 3, 5, 3, 7, 1, 9, 3]
Remove the first occurrence of 3 from the said array:
New array: [1, 5, 3, 7, 1, 9, 3]

**Comment by NazarchykM** [comment]
Done

**Comment by kekslv** [comment]
The program should sear a number in the array and remove it, do not remove by index

**Comment by NazarchykM** [comment]
Now it is done
